<form class="form-horizontal" method="post" action="/smart/configuration">
    <?php if ($msg != ''): ?>
        <div class="alert alert-info">
            <div class="">
                <?= $msg ?>
            </div>
        </div>
    <?php endif; ?>

    <?php foreach ($devices as $item): ?>
        <h4><?= $item['name'] ?></h4>
        <hr>
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">
                URL <?= $item['type'] ?>
            </label>

            <div class="col-sm-10">
                <input type="url" name="status[<?= $item['id'] ?>]" class="form-control" id="inputEmail3"
                       placeholder="URL <?= $item['type'] ?>" value="<?= $item['url'] ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">
                URL <?= $item['on']['type'] ?>
            </label>

            <div class="col-sm-10">
                <input type="url" name="on[<?= $item['on']['id'] ?>]" class="form-control" id="inputEmail3"
                       placeholder="URL <?= $item['on']['type'] ?>" value="<?= $item['on']['url'] ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">
                URL <?= $item['off']['type'] ?>
            </label>

            <div class="col-sm-10">
                <input type="url" name="off[<?= $item['off']['id'] ?>]" class="form-control" id="inputEmail3"
                       placeholder="URL <?= $item['off']['type'] ?>" value="<?= $item['off']['url'] ?>">
            </div>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
