<div class="row">
    <div class="result"></div>
    <?php foreach ($url as $item): ?>
        <div class="col-xs-12">
            <span class="uri<?= $item['id'] ?>" data-url="<?= $item['url'] ?>">
                <?= $item['url'] ?>
            </span>
            <button class="btn btn-info btn-xs"><?= $item['type'] ?></button>
            <button class="btn btn-xs btn-exe btn-danger" data-id="<?= $item['id'] ?>">Exec</button>
            <hr>
        </div>
    <?php endforeach; ?>
</div>